#!/bin/python3.8

import sys
import argparse
import colorama

from backend import add, build, init, run, clean

modules = {
    "init": init,
    "build": build,
    "add": add,
    "run": run,
    "clean": clean,
    # new
    # doc (doxygen?)
}

colorama.init(convert=True if "win" in sys.platform.lower() else None)

parser = argparse.ArgumentParser(
    prog="modulos", description="Compile a C++ binary")
parser.add_argument("operation", choices=modules.keys())

# init-specifics
parser.add_argument("--name", default=None,
                    help="Name of module, set only on `init`")
parser.add_argument("--compiler", default=None,
                    help="Path to compiler, set only on `init`")
parser.add_argument("--version", default=None,
                    help="C++ version, set only on `init`, only set the integer, such as `--version=17`")

# any-command usage
parser.add_argument("--dir", default=".",
                    help="Directory for modulos to perform the action on")

args = parser.parse_args()
args.dir += ("/" if args.dir[-1] != "/" else "")
modules[args.operation].main(args)
